### ISSUE TITLE
ReferenceError at assertion with array comparision

### ISSUE THREAD

**Issue by BelAn97** [blablameh/MochawesomePlusPlus#1]
it('Test', function() {
expect([1,2,3]).to.have.members([2,3,4]);
});

Exception:
Problem with mochawesome: ReferenceError: indexOf is not defined
    at stringify (c:\JS_Tests\pp_ui\node_modules\mochawesomeplusplus\lib\templateHelper.js:16:11)
    at Object.exports.printDifferences (c:\JS_Tests\pp_ui\node_modules\mochawesomeplusplus\lib\templateHelper.js:62:26)
    at Object.Handlebars.registerPartial.Handlebars.template.13 (c:\JS_Tests\pp_ui\node_modules\mochawesomeplusplus\lib\templates.js:375:133)
    at prog (c:\JS_Tests\pp_ui\node_modules\handlebars\dist\cjs\handlebars\runtime.js:193:15)
    at Object.<anonymous> (c:\JS_Tests\pp_ui\node_modules\handlebars\dist\cjs\handlebars\base.js:115:14)
    at Object.Handlebars.registerPartial.Handlebars.template.main (c:\JS_Tests\pp_ui\node_modules\mochawesomeplusplus\lib\templates.js:409:39)
    at ret (c:\JS_Tests\pp_ui\node_modules\handlebars\dist\cjs\handlebars\runtime.js:159:30)
    at Object.invokePartial (c:\JS_Tests\pp_ui\node_modules\handlebars\dist\cjs\handlebars\runtime.js:218:12)
    at Object.invokePartialWrapper [as invokePartial] (c:\JS_Tests\pp_ui\node_modules\handlebars\dist\cjs\handlebars\runtime.js:61:39)
    at Object.Handlebars.registerPartial.Handlebars.template.26 (c:\JS_Tests\pp_ui\node_modules\mochawesomeplusplus\lib\templates.js:301:23)

**Comment by blablameh** [comment]
Thanks for pointing this out.
I will start working on the fix and get this sorted out over the weekend

**Comment by blablameh** [comment]
This issue has been fixed.
Thanks :)
